Hotfix broken pre-commit hook
Source: https://github.com/msupply-foundation/remote-server/commit/60a880406cf09640498f4781bfeccbb3621867c8

diff --git a/server/.githooks/pre-commit b/server/.githooks/pre-commit
--- a/server/.githooks/pre-commit
+++ b/server/.githooks/pre-commit
@@ -10,18 +10,30 @@ if [ "$(git config --type=bool hooks.norustfmt)" = "true" ]; then
 	exit 0
 fi
 
+echo "Format checking staged rust files..."; echo
+
 # Iterate staged rust source files to check for incorrectly formatted code.
 COMMIT_OK=0
 for file in $(git diff --name-only --staged | grep -E "*.rs"); do
-	rustfmt --check "$file" 2>/dev/null
-	if [ $? -ne 0 ]; then 
-		echo "$file"
-		COMMIT_OK=1
+	echo -n  "$file - "	
+	rustfmt --check "$file" >/dev/null
+	if [ $? -eq 0 ]; then 
+		echo -e "\033[0;32mOK\033[0m"
+	else
+		echo -e "\033[0;31mERROR\033[0m"		
+		COMMIT_OK=1		
 	fi
 done
 
 # Commit staged files only if no incorrectly formatted rust code is detected.
 if [ $COMMIT_OK -ne 0 ]; then
-	echo; echo "The above files contain improperly formatted code. Format with \`cargo fmt\` and try again."
+	# Incorrectly formatted rust code detected. Abort commit.
+	echo; echo "Improperly formatted code detected. Format with \`cargo fmt\` and try again."
+	exit 1
+else
+	# No improperly formatted rust code detected. Commit OK. 
+	echo
+	exit 0
 fi
-exit $COMMIT_OK
+
+
